service: serverless
frameworkVersion: "^3.12.0"

provider:
  name: yandex-cloud
  runtime: nodejs16

plugins:
  - serverless-dotenv-plugin
  - "@yandex-cloud/serverless-plugin"

package:
  patterns:
    - '!**'
    - package.json
    - package-lock.json
    - dist/*.js

functions:
  example:
    name: example
    handler: dist/index.handler
    memorySize: 128
    timeout: 5
    account: example-sa
    # environment:
    #   ENV: env

  # trigger:
  #   handler: dist/trigger.trigger
  #   memorySize: 128
  #   timeout: 5
  #   events:
  #     - cron:
  #         expression: "* * * * ? *"
  #         account: trigger-sa
  #         retry:
  #           attempts: 1
  #           interval: 10

resources:
  example-sa:
    type: yc::ServiceAccount
    roles:
      - editor
  # trigger-sa:
  #   type: yc::ServiceAccount
  #   roles:
  #     - serverless.functions.invoker
